### PR TITLE
Added Docker client to support `rancher exec`

### PR DESCRIPTION
**Pull request by iBobik**
Fixes rancher/rancher#8771

### CODE REVIEW

**Comment by deniseschannon** [comment]
@iBobik The `master` branch was refactored for Rancher 2.0, but with the changes that we've made in the latest tech preview, we will be making a new CLI. 

If you would like to help contribute for changes to be made in the current Rancher 1.6.x line, you will need to switch and rebase to use the `v1.6` branch.

**Comment by iBobik** [comment]
@deniseschannon Thank you for info. Changes I made are useable for 1.6 and 2.0, aren't?

If yes why not to merge them to both `master` and `v1.6`?

**Comment by iBobik** [comment]
Just for my information, how is that division to two branches related with
semantic versioning what can be seen in tags?
https://hub.docker.com/r/rancher/cli/tags/



Jan Pobořil

2018-01-29 4:18 GMT+01:00 Denise <notifications@github.com>:

**Comment by deniseschannon** [comment]
If i change the base branch to `v1.6`, there are lots of unnecessary commits as well as the fact that it cannot be merged in. Therefore whatever you have is not merge-able into v1.6. As for master, due to the fundamental changes in 2.0, we are going to be creating a new repo for the CLI that will work with 2.0, so the `master` branch of this will not be used. 

Nothing was every released with the `master` branch for 2.0, so all the published versions of CLI are for he `1.x` line.

**Comment by iBobik** [comment]
Here is pull request for v1.6: https://github.com/rancher/cli/pull/113

**Comment by cjellick** [comment]
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

**Pull request closed without merging**
