### PR TITLE
throw error if we try to parse an answers file but don't find any

### PR DESCRIPTION
**Pull request by wjimenez5271**

### CODE REVIEW

**Comment by wjimenez5271** [comment]
https://github.com/rancher/rancher/issues/9665

**Comment by cjellick** [comment]
Offline discussion determine that the proper fix is going to be to regex each line.

**Comment by wjimenez5271** [comment]
@cjellick see above refactor using regex

**Comment by wjimenez5271** [comment]
this PR doesn't apply any more since the refactor

**Pull request closed without merging**
