### PR TITLE
add catalog refresh

### PR DESCRIPTION
**Pull request by blakeroberts-wk**
Allows refreshing catalogs via the CLI.

For example:
```bash
# Refresh a catalog
$ rancher catalog refresh foo

 # Refresh multiple catalogs
$ rancher catalog refresh foo bar baz

 # Refresh all catalogs
$ rancher catalog refresh --all
```

### CODE REVIEW

**Comment by blakeroberts-wk** [comment]
fixes https://github.com/rancher/rancher/issues/13834

**Comment by loganhz** [comment]
Thanks for the PR!

**Comment by gitlawr** [comment]
Refresh action runs asynchronously, but it would be helpful in CI scenarios that we can wait until it completes and succeeds. Would you like to address that in this pr? For example, add  `--wait,-w` and `--wait-timeout` options and wait for catalogs' state to be active.

**Comment by cjellick** [comment]
@dramich to review

**Comment by dramich** [comment]
With the changes to catalogs now being at three levels (global, cluster and project) the `--all` flag needs to be investigated to ensure it's going to operate as expected. The concern is running with the `--all` flag could set off the update of all catalogs in rancher, which could end up being a lot and may not be what the user is intending (update all of **their** catalogs vs all catalogs in rancher).

**Comment by cjellick** [comment]
@mrajashree will need to confirm how that action behaves with the changes introduced for cluster and project level catalogs

**Comment by blakeroberts-wk** [comment]
@gitlawr I agree that from a CI perspective, timeouts would be nice. I am not sure how permissions work, but I don't think it's a concern. If we have permission to get a `Catalog.ByID()`, we can grab the `catalog.State` and check if it is `active` correct?

I started working on the timeout implementation. I haven't been able to test it manually yet. Once I have verified the functionality I can push the commit to this branch/pr.

I actually did timeouts twice (first pass was more complex than necessary).
1. timeouts using goroutines and channels
    - https://github.com/blakeroberts-wk/cli/compare/add_catalog_refresh...blakeroberts-wk:add_catalog_refresh_with_timeout
1. normal people timeouts
    - https://github.com/blakeroberts-wk/cli/compare/add_catalog_refresh...blakeroberts-wk:add_catalog_refresh_with_timeout_no_goroutine

**Comment by blakeroberts-wk** [comment]
I have timeouts working here: https://github.com/blakeroberts-wk/cli/tree/add_catalog_refresh_with_timeout_no_goroutine

Let me know if you'd like me to push the changes to this branch.

<details>
<summary>Example output</summary>
<p>

```bash
$ rancher --debug catalog refresh helm --wait --wait-timeout=1 && rancher catalog ls -v
DEBU[0000] catalog: waiting for catalogs to become active (timeout=1s)
DEBU[0000] catalog: waiting for helm to become active
FATA[0002] catalog: timed out waiting for refresh
```

```bash
$ rancher --debug catalog refresh helm --wait --wait-timeout=1 && rancher catalog ls -v
DEBU[0000] catalog: waiting for catalogs to become active (timeout=1s)
DEBU[0000] catalog: waiting for helm to become active
DEBU[0001] catalog: waited for 929.037042ms seconds
ID            NAME          URL                                                  BRANCH    KIND      STATE
helm          helm          https://kubernetes-charts.storage.googleapis.com/    master    helm      active
library       library       https://git.rancher.io/charts                        master    helm      active
```

```bash
$ rancher --debug catalog refresh --all --wait --wait-timeout=1 && rancher catalog ls -v
DEBU[0000] catalog: waiting for catalogs to become active (timeout=1s)
DEBU[0000] catalog: waiting for helm to become active
FATA[0001] catalog: timed out waiting for refresh
```

```bash
$ rancher --debug catalog refresh --all --wait --wait-timeout=5 && rancher catalog ls -v
DEBU[0000] catalog: waiting for catalogs to become active (timeout=5s)
DEBU[0000] catalog: waiting for helm to become active
DEBU[0001] catalog: waiting for library to become active
DEBU[0002] catalog: waited for 1.519280857s seconds
ID            NAME          URL                                                  BRANCH    KIND      STATE
helm          helm          https://kubernetes-charts.storage.googleapis.com/    master    helm      active
library       library       https://git.rancher.io/charts                        master    helm      active
```

</p>
</details>

**Comment by cjellick** [comment]
Since everyone wants this for automation purposes, I think this needs the wait logic with it. It is of limited use in automation without it

**Comment by cjellick** [comment]
@blakeroberts-wk i made some comments on your wait logic. Are you going to have the bandwidth to add the wait logic in and make the changes I requested? We are keen on getting this in, so if you don't have the bandwidth, I would need to know.

**Comment by blakeroberts-wk** [comment]
@cjellick I have made the requested changes. Any further review?

**Comment by cjellick** [comment]
Thanks @blakeroberts-wk
LGTM

**Pull request merged**
