### PR TITLE
Fix cli formatting option to print yaml

### PR DESCRIPTION
**Pull request by yogeshmundada**
Issue: https://github.com/rancher/rancher/issues/27661

Fixed the format specific bug by upgrading the version of urfave/cli

```
yogesh@Yogeshs-MacBook-Pro:~/go/src/rancher/cli$ ./cli inspect --type cluster local --format yaml
agentFeatures:
  dashboard: true
agentImage: rancher/rancher-agent:master-head
agentImageOverride: ""
allocatable:
  cpu: "0"
  memory: "0"
  pods: "0"
annotations:
  authz.management.cattle.io/creator-role-bindings: '{"created":["cluster-owner"],"required":["cluster-owner"]}'
  lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true"
  lifecycle.cattle.io/create.cluster-provisioner-controller: "true"
  lifecycle.cattle.io/create.cluster-scoped-gc: "true"
  lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: "true"
  provisioner.cattle.io/ke-driver-update: updated
answers:
  clusterId: null
  projectId: null
  type: /v3/schemas/answer
appliedEnableNetworkPolicy: false
appliedPodSecurityPolicyTemplateId: ""
appliedSpec:
  agentImageOverride: ""
  answers:
    clusterId: null
    projectId: null
    type: /v3/schemas/answer
  clusterTemplateId: null
  clusterTemplateRevisionId: null
  defaultClusterRoleForProjectMembers: null
  defaultPodSecurityPolicyTemplateId: null
  description: ""
  desiredAgentImage: ""
  desiredAuthImage: ""
  displayName: ""
  dockerRootDir: /var/lib/docker
  enableClusterAlerting: false
  enableClusterMonitoring: false
  enableNetworkPolicy: null
  internal: false
  localClusterAuthEndpoint:
    enabled: false
    type: /v3/schemas/localClusterAuthEndpoint
  type: /v3/schemas/clusterSpec
  windowsPreferedCluster: false
authImage: ""
baseType: cluster
capabilities:
  loadBalancerCapabilities:
    healthCheckSupported: false
    type: /v3/schemas/loadBalancerCapabilities
  nodePoolScalingSupported: false
  pspEnabled: false
  type: /v3/schemas/capabilities
capacity:
  cpu: "0"
  memory: "0"
  pods: "0"
clusterTemplateId: null
clusterTemplateRevisionId: null
componentStatuses:
- conditions:
  - message: ok
    status: "True"
    type: Healthy
  name: controller-manager
  type: /v3/schemas/clusterComponentStatus
- conditions:
  - message: '{"health":"true"}'
    status: "True"
    type: Healthy
  name: etcd-0
  type: /v3/schemas/clusterComponentStatus
- conditions:
  - message: ok
    status: "True"
    type: Healthy
  name: scheduler
  type: /v3/schemas/clusterComponentStatus
conditions:
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: BackingNamespaceCreated
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: DefaultProjectCreated
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: SystemProjectCreated
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: InitialRolesPopulated
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: CreatorMadeOwner
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: Pending
- lastUpdateTime: "2020-06-30T19:02:57-07:00"
  status: "True"
  type: Provisioned
- lastUpdateTime: "2020-06-30T19:03:07-07:00"
  status: "True"
  type: Waiting
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: NoDiskPressure
- lastUpdateTime: "2020-06-30T19:02:52-07:00"
  status: "True"
  type: NoMemoryPressure
- lastUpdateTime: "2020-06-30T19:02:55-07:00"
  status: "False"
  type: AlertingEnabled
- lastUpdateTime: "2020-06-30T19:02:56-07:00"
  status: "True"
  type: SystemAccountCreated
- lastUpdateTime: "2020-06-30T19:04:25-07:00"
  status: "True"
  type: AgentDeployed
- lastUpdateTime: "2020-06-30T19:02:57-07:00"
  status: "True"
  type: Updated
- lastUpdateTime: "2020-06-30T19:02:57-07:00"
  status: "True"
  type: GlobalAdminsSynced
- lastUpdateTime: "2020-06-30T19:03:07-07:00"
  status: "True"
  type: Ready
- lastUpdateTime: "2020-06-30T19:04:25-07:00"
  status: "False"
  type: PrometheusOperatorDeployed
created: "2020-07-01T02:02:52Z"
createdTS: 1593568972000
creatorId: user-ph5pg
defaultClusterRoleForProjectMembers: null
defaultPodSecurityPolicyTemplateId: null
description: ""
desiredAgentImage: ""
desiredAuthImage: ""
dockerRootDir: /var/lib/docker
driver: imported
enableClusterAlerting: false
enableClusterMonitoring: false
enableNetworkPolicy: null
id: local
internal: true
istioEnabled: false
labels:
  cattle.io/creator: norman
limits:
  cpu: "0"
  memory: "0"
  pods: "0"
localClusterAuthEndpoint:
  enabled: false
  type: /v3/schemas/localClusterAuthEndpoint
name: local
nodeCount: 1
nodeVersion: 0
requested:
  cpu: "0"
  memory: "0"
  pods: "0"
state: active
transitioning: "no"
transitioningMessage: ""
type: cluster
uuid: 57185828-595f-4557-8565-2323dbce6202
version:
  buildDate: "2019-09-18T14:27:17Z"
  compiler: gc
  gitCommit: 2bd9643cee5b3b3a5ecbd3af49d09018f0773c77
  gitTreeState: clean
  gitVersion: v1.16.0
  goVersion: go1.12.9
  major: "1"
  minor: "16"
  platform: linux/amd64
  type: /v3/schemas/info
windowsPreferedCluster: false

yogesh@Yogeshs-MacBook-Pro:~/go/src/rancher/cli$
```

### CODE REVIEW

**Comment by deniseschannon** [comment]
@yogeshmundada this will most likely fix this issue as well, right? https://github.com/rancher/rancher/issues/27376

**Comment by deniseschannon** [comment]
If possible, I think we should release a new CLI independent of Rancher to fix the parsing bugs that will break a lot of people's automation. What do you think @dramich ?

**Comment by dramich** [comment]
> If possible, I think we should release a new CLI independent of Rancher to fix the parsing bugs that will break a lot of people's automation. What do you think @dramich ?

Yeah, that sounds good.

**Comment by yogeshmundada** [comment]
@deniseschannon I am testing if the other issue gets fixed.

**Pull request merged**
